### ISSUE TITLE
Support Rails scopes

### ISSUE THREAD

**Issue by petRUShka** [ivalkeen/guard-ctags-bundler#31]
Please add support for rails scopes.

`--regex-ruby=/^[ \t]*scope[ \t]*:([a-zA-Z0-9_]+)/\1/`

Sources:
1. https://coderwall.com/p/ycql_q/add-activerecord-scopes-to-ctags
2. http://stackoverflow.com/questions/9512285/how-can-i-configure-vim-ctags-to-recognize-rails-activerecord-scope-definition

**Comment by ivalkeen** [comment]
It is already supported. You can override `arguments` configuration options to set any arguments or just put it into your `~/.ctags` file.

**Comment by petRUShka** [comment]
I've meant by default. It seems to be very convenient default. Is there reason not to include scope support by default?
